name: build and test

on: [push]

jobs:
  compliance:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Advance Security Compliance Action
        uses: GeekMasher/advanced-security-compliance@v1.6
        with:
          policy: GeekMasher/security-queries
          policy-path: policies/default.yml

          token: ${{ secrets.ACCESS_TOKEN }}

          argvs: '--disable-dependabot --disable-secret-scanning --disable-code-scanning'

  build:
    needs: compliance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup NodeJS 14
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Webpack build
          run: npm run build
