name: build and release

on: [push]
#  pull_request:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup NodeJS 14
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Webpack build
        run: npm run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: get-npm-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Print version
        run: echo ${{ steps.package-version.outputs.current-version }}

      - name: Get package version
        uses: koj-co/package-version-action@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Print version
        run: echo ${{ steps.package-version.outputs.package-version }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: itatm/digiwf-load-test:latest,itatm/digiwf-load-test:${{ steps.package-version.outputs.package-version }}
